-- ============================================================
-- Screenplay Studio — Work Time Tracking Migration
-- Run in Supabase SQL Editor (Dashboard > SQL Editor)
-- Safe to re-run — uses IF NOT EXISTS / OR REPLACE throughout
-- ============================================================

-- ──────────────────────────────────────────────────────────────
-- 1. work_sessions TABLE
--    One row per browser tab session per project.
--    duration_seconds accumulates via heartbeat API.
--    session_key is a client-generated UUID stored in
--    sessionStorage (cleared on tab close → new session each time).
-- ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS work_sessions (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  project_id          UUID        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  -- context: 'script', 'documents', 'arc-planner', 'general', etc.
  context             TEXT        NOT NULL DEFAULT 'general',
  -- date the session started (UTC date, used for daily roll-ups)
  date                DATE        NOT NULL DEFAULT CURRENT_DATE,
  -- total seconds credited to this session (heartbeat-incremented)
  duration_seconds    INTEGER     NOT NULL DEFAULT 0,
  -- last time a heartbeat was received (for rate-limit / gap checks)
  last_heartbeat_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- idempotency key generated by the client (one per tab/page-load)
  session_key         TEXT        NOT NULL,
  CONSTRAINT uq_work_session UNIQUE (user_id, project_id, session_key)
);

COMMENT ON TABLE work_sessions IS
  'Tracks active work time per user per project, accumulated via 30-second heartbeats.
   Smart idle detection and thinking-grace credits are applied server-side.
   Each browser tab generates a unique session_key so simultaneous tabs are tracked separately.';

COMMENT ON COLUMN work_sessions.duration_seconds IS
  'Accumulated working seconds. Incremented 30s per heartbeat + optional grace (≤600s)
   for short breaks (5-20 min away). Capped server-side — cannot be manipulated client-side.';

COMMENT ON COLUMN work_sessions.session_key IS
  'UUID generated by the client on page load, stored in sessionStorage.
   Closes the exploit window of replaying old session_keys — each tab gets one.';


-- ──────────────────────────────────────────────────────────────
-- 2. ROW LEVEL SECURITY
-- ──────────────────────────────────────────────────────────────

ALTER TABLE work_sessions ENABLE ROW LEVEL SECURITY;

-- Users can insert sessions for themselves only
DROP POLICY IF EXISTS "ws_insert_own" ON work_sessions;
CREATE POLICY "ws_insert_own" ON work_sessions
  FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- Users can update their own sessions only
DROP POLICY IF EXISTS "ws_update_own" ON work_sessions;
CREATE POLICY "ws_update_own" ON work_sessions
  FOR UPDATE
  USING (user_id = auth.uid());

-- Anyone on the project team can read work sessions for that project
-- (so project owners can see team hours)
DROP POLICY IF EXISTS "ws_select_project_member" ON work_sessions;
CREATE POLICY "ws_select_project_member" ON work_sessions
  FOR SELECT
  USING (
    project_id IN (
      -- project creator
      SELECT id FROM projects WHERE created_by = auth.uid()
      UNION
      -- project members
      SELECT project_id FROM project_members WHERE user_id = auth.uid()
    )
  );

-- Users can delete their own sessions (e.g. data export / GDPR)
DROP POLICY IF EXISTS "ws_delete_own" ON work_sessions;
CREATE POLICY "ws_delete_own" ON work_sessions
  FOR DELETE
  USING (user_id = auth.uid());


-- ──────────────────────────────────────────────────────────────
-- 3. PERFORMANCE INDEXES
-- ──────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_work_sessions_user_project
  ON work_sessions (user_id, project_id);

CREATE INDEX IF NOT EXISTS idx_work_sessions_project_date
  ON work_sessions (project_id, date DESC);

CREATE INDEX IF NOT EXISTS idx_work_sessions_session_key
  ON work_sessions (session_key);

CREATE INDEX IF NOT EXISTS idx_work_sessions_last_heartbeat
  ON work_sessions (last_heartbeat_at DESC);


-- ──────────────────────────────────────────────────────────────
-- 4. HELPER VIEWS (admin / analytics)
-- ──────────────────────────────────────────────────────────────

-- Daily work hours per user per project (last 90 days)
CREATE OR REPLACE VIEW work_hours_by_day AS
SELECT
  user_id,
  project_id,
  date,
  SUM(duration_seconds)                    AS total_seconds,
  ROUND(SUM(duration_seconds) / 3600.0, 2) AS hours
FROM work_sessions
WHERE date >= CURRENT_DATE - INTERVAL '90 days'
GROUP BY user_id, project_id, date
ORDER BY date DESC;

-- Total hours per user per project (all time)
CREATE OR REPLACE VIEW work_hours_by_user AS
SELECT
  user_id,
  project_id,
  SUM(duration_seconds)                    AS total_seconds,
  ROUND(SUM(duration_seconds) / 3600.0, 2) AS total_hours,
  MIN(date)                                AS first_session,
  MAX(date)                                AS last_session,
  COUNT(DISTINCT date)                     AS days_worked
FROM work_sessions
GROUP BY user_id, project_id
ORDER BY total_seconds DESC;

-- Context breakdown (how time is split between script editor, documents, etc.)
CREATE OR REPLACE VIEW work_hours_by_context AS
SELECT
  user_id,
  project_id,
  context,
  SUM(duration_seconds)                    AS total_seconds,
  ROUND(SUM(duration_seconds) / 3600.0, 2) AS hours
FROM work_sessions
GROUP BY user_id, project_id, context
ORDER BY total_seconds DESC;

-- Platform-wide work stats (for admin panel)
CREATE OR REPLACE VIEW admin_work_stats AS
SELECT
  p.id                                           AS project_id,
  p.title                                        AS project_title,
  COUNT(DISTINCT ws.user_id)                     AS contributors,
  COUNT(DISTINCT ws.id)                          AS total_sessions,
  SUM(ws.duration_seconds)                       AS total_seconds,
  ROUND(SUM(ws.duration_seconds) / 3600.0, 2)   AS total_hours,
  MAX(ws.last_heartbeat_at)                      AS last_activity
FROM projects p
LEFT JOIN work_sessions ws ON ws.project_id = p.id
GROUP BY p.id, p.title
ORDER BY total_seconds DESC NULLS LAST;

-- Grant read access to authenticated users (RLS on work_sessions
-- already limits what each user can see)
GRANT SELECT ON work_hours_by_day     TO authenticated;
GRANT SELECT ON work_hours_by_user    TO authenticated;
GRANT SELECT ON work_hours_by_context TO authenticated;
GRANT SELECT ON admin_work_stats      TO authenticated;


-- ──────────────────────────────────────────────────────────────
-- 5. CLEANUP FUNCTION
--    Remove stale sessions (last heartbeat > 24h ago and incomplete)
--    Call this periodically via pg_cron or a Supabase Edge Function.
-- ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION cleanup_stale_work_sessions()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  DELETE FROM work_sessions
  WHERE last_heartbeat_at < now() - INTERVAL '24 hours'
    AND duration_seconds < 60; -- sessions under 1 minute that went stale
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$;

COMMENT ON FUNCTION cleanup_stale_work_sessions() IS
  'Removes work sessions that are older than 24h and credited less than 60 seconds
   (i.e. the user opened a page then left immediately). Safe to call repeatedly.';


-- ──────────────────────────────────────────────────────────────
-- SUMMARY
-- ──────────────────────────────────────────────────────────────
--
-- NEW TABLE:    work_sessions
--   • Heartbeat-based time tracking, server-side accumulation
--   • Smart grace period for short breaks (5-20 min away → +50% of break, max 10 min)
--   • Anti-exploit: auth required, rate-limited server-side (≥20s between heartbeats),
--     grace capped at 600s, sessions keyed per tab via sessionStorage UUID
--   • RLS: users own their rows; project team can read project totals
--
-- NEW VIEWS:    work_hours_by_day, work_hours_by_user,
--               work_hours_by_context, admin_work_stats
--
-- NEW FUNCTION: cleanup_stale_work_sessions()
--
-- NEW INDEXES:  idx_work_sessions_user_project, idx_work_sessions_project_date,
--               idx_work_sessions_session_key, idx_work_sessions_last_heartbeat
-- ============================================================
