version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    depends_on:
      - media-server

  media-server:
    build:
      context: .
      dockerfile: Dockerfile.media-server
    ports:
      - '8000:8000'
      - '1935:1935'
    volumes:
      - media-data:/media

volumes:
  media-data:
